### ISSUE TITLE
Refactor rego for each baseline to include detailed message in report

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#90]
As part of implementing the Multiple OU's use case for each of the baseline, the earlier implemented detailed report messages will get replaced by a more generic message on whether the baseline policy is complaint in all the OU's or not.

Since the detailed report message is similar to the report details on M365 and was added as per request (on the M365 side), this may be something we may need to revisit and implement on the GWS side as well.

To be able to re-use the existing detailed message from each baseline, this issue will serve as an epic for each of the issues/baseline.

In each of these issues, you may find the obsolete code with the detailed report messages that can be re-used whenever this feature is added to the code base. 

- [x] #89
- [x] #88
- [x] #87 
- [x] #86 
- [x] #85 
- [x] #84 
- [x] #174 
- [x] #173
- [x] #177
- [x] #259

**Comment by adhilto** [comment]
Documenting the approach I used on https://github.com/cisagov/ScubaGoggles/pull/176:

1. Created a new function in the Utils file `ReportDetailsDetailedOU`. Because it's in the Utils file, when implementing this change for other baselines, there won't be any need to implement this again.
2. For each control:
    a. Determine an appropriate `SettingDescription` for the setting in question
    b. Determine if the `LastEvent.NewValue` value is user-friendly; if not, create a `GetFriendlyValuex_x` function that translates the values to user-friendly strings (see #176 for examples)
    c. Refactor the `NonCompliantOUsx_x` rule so that it includes both "Name" and "Value" keys
    d. Change the `ReportDetailsOUs` call to `ReportDetailsDetailedOU` (include the SettingDescription from step a)
    e. Test and ensure it works as expected
    f. Update the unit tests to reflect the change

Scenarios that aren't covered by the above workflow:
- Handling settings that aren't controlled at the OU level
- Controls that depend on multiple settings

**Comment by adhilto** [comment]
See #204 for how this would look post group bug fix.
